# Generated by Django 4.1 on 2022-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_gender_athlete_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("show_total_distance", models.BooleanField(default=False)),
                (
                    "route_gpx",
                    models.FileField(blank=True, null=True, upload_to="route-gpx"),
                ),
                (
                    "route_image",
                    models.FileField(blank=True, null=True, upload_to="route-image"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="elapsed_time",
            field=models.DurationField(
                verbose_name="Elapsed Time (MM:SS) or (HH:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(verbose_name="Start Time (DD/MM/YYYY HH:MM)"),
        ),
    ]
