# Generated by Django 4.1 on 2022-08-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_event_alter_activity_elapsed_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="event",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.event"
            ),
            preserve_default=False,
        ),
    ]
