# Generated by Django 4.1 on 2022-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_race_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_html",
            field=models.TextField(default=""),
        ),
    ]
