# Generated by Django 4.1 on 2022-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_event_description_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
