# Generated by Django 4.1 on 2022-09-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_event_relay"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTeamAthlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.athlete"
                    ),
                ),
                (
                    "event_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.eventteam"
                    ),
                ),
            ],
        ),
    ]
